---
# credentials
barman_login: barman
barman_password: barmanpassword
streaming_barman_login: streaming_barman
streaming_barman_password: streaming_barman_password

# specific variables
db_path: /var/lib/pgsql/11/data
pg_version: 11
